# Generated by Django 2.1.3 on 2018-11-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkplace',
            name='legit_delta',
            field=models.IntegerField(default=60, verbose_name='Temps min en minutes entre 2 passage'),
            preserve_default=False,
        ),
    ]
