# Generated by Django 2.1.3 on 2019-03-21 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('checker', '0003_check_seems_legit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                (
                    'check_place',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checker.CheckPlace')),
            ],
        ),
    ]
